import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Dancing_Script } from 'next/font/google';
import { Cinzel } from 'next/font/google';
import { Comfortaa } from 'next/font/google';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({ subsets: ['latin'] });
const cinzel = Cinzel({ subsets: ['latin'] });

const comfortaa = Comfortaa({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dancingScript.className} ${cinzel.className} ${comfortaa.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
